name: Release PipeDream Module

on:
  push:
    tags:
      - 'v*-alpha'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Package module
      shell: pwsh
      run: Compress-Archive -Path 'src/PipeDream/*' -DestinationPath 'PipeDream_${{ github.ref_name }}.zip'

    - name: ${{ github.ref_name }}
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ${{ github.workspace }}\.github\release-notes\${{ github.ref_name }}.md
        prerelease: true
        draft: true
        files: PipeDream_${{ github.ref_name }}.zip

    # - name: Publish PowerShell Module
    #   uses: natescherer/publish-powershell-action@v1
    #   with:
    #     token: ${{ secrets.PSGALLERY_API_KEY }}
    #     target: gallery
    #     path: src\PipeDream\PipeDream.psd1