name: Release PipeDream Module

on:
  push:
    tags:
      - 'v*-alpha'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Package module
      # shell: pwsh
      # run: Compress-Archive -Path 'src/PipeDream/*' -DestinationPath 'PipeDream_${{ github.ref_name }}.zip'
      run: echo ${{ github.ref_name }}

    # - name: Publish PowerShell Module
    #   uses: natescherer/publish-powershell-action@v1
    #   with:
    #     token: ${{ secrets.PSGALLERY_API_KEY }}
    #     target: gallery
    #     path: src\PipeDream\PipeDream.psd1
