name: Test PowerShell Module

on:
  push:
    paths:
      - src/**
      - tests/**
      - .github/workflows/tests.yml
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Pester tests
        shell: pwsh
        run: |
          $testResults = Invoke-Pester -Path ./tests -PassThru
          