name: Test PowerShell Module
on: push

jobs:
  test:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Pester tests
        shell: pwsh
        run: |
          $testResults = Invoke-Pester -Path ./tests -PassThru
          