name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Pester tests
        shell: pwsh
        run: |
          $testResults = Invoke-Pester -Path ./tests -Output Detailed -PassThru
          if ($testResults.FailedCount -ne 0) {
              Write-Error "One or more tests failed."
              exit 1
          }